# file: bossjones.common/tasks/debug_packages.yml
---
- name: install debug packages
  apt: pkg={{ item }} state=present
  with_items:
  - python-dbg
  - libgtk-3-0-dbg
  - python-gi-dbg
  - glib-networking-dbg
  - libdbus-c++-dbg
  - libdbus-glib-1-2-dbg
  - libglib2.0-0-dbg
  - libpulse-mainloop-glib0-dbg
  - libdbus-glib-1-2-dbg
  - python-dbus-dbg
  - libdbus-glib-1-2-dbg
  tags:
  - debug_packages
  - dbg
