# file: bossjones.common/tasks/gnome_gtk_prereqs.yml
---

- name: Read the gnome_gtk_prereqs variables
  include_vars: "gnome_gtk_prereqs.yml"

- name: Make sure the gnome_gtk_prereqs packages are installed (Debian)
  apt:
    name: "{{item}}"
    state: present
  with_items: gnome_gtk_prereqs
  sudo: yes
  tags:
  - gnome
  - packages
  - install_packages
