# file: bossjones.common/tasks/main.yml
---

- name: Update apt
  apt: update_cache=yes
  sudo: yes

- name: setup motd
  copy: src=etc/motd
        dest=/etc/motd
        owner=root
        group=root
        mode=0644
  tags:
  - motd

- name: provision scarlett node
  include: build_essentials.yml

- name: bootstrap
  include: bootstrap.yml

# - name: guest additions
#   include: setup_guestadditions.yml

- name: setup_sshd
  include: setup_sshd.yml

- name: ntp
  include: setup_ntp.yml

- name: pulseaudio
  include: setup_pulseaudio.yml

# - name: hgdf
#   include: setup_espeak.yml

# - name: hgdf
#   include: setup_gstreamer.yml

# - name: hgdf
#   include: gnome_gtk_prereqs.yml

# - name: hgdf
#   include: setup_python.yml

# - name: hgdf
#   include: setup_scarlett_user.yml

# - name: hgdf
#   include: setup_scarlett.yml

# - name: hgdf
#   include: setup_pocketsphinx.yml

  # include: bootstrap.yml
  # include: setup_guestadditions.yml
  # include: setup_sshd.yml
  # include: setup_ntp.yml
  # include: setup_pulseaudio.yml
  # include: setup_espeak.yml
  # include: setup_gstreamer.yml
  # include: gnome_gtk_prereqs.yml
  # include: setup_python.yml
  # include: setup_scarlett_user.yml
  # include: setup_scarlett.yml
  # include: setup_pocketsphinx.yml
