# file: bossjones.common/tasks/setup_python.yml
---

- name: Read the setup_python variables
  include_vars: "setup_python.yml"

- name: Make sure the setup_python packages are installed (Debian)
  apt:
    name: "{{item}}"
    state: present
  with_items: setup_python
  sudo: yes

- name: install pip
  easy_install: name=pip

- name: install virtualenv
  pip: name=virtualenv
       state=present

- name: install virtualenvwrapper
  pip: name=virtualenvwrapper
       state=present

- name: install ipython
  pip: name=ipython
       state=present

- name: install numpy
  pip: name=numpy
       state=present

- name: pip install requests[security]
  pip: name=requests[security]
       state=present

# pip install --upgrade pip

- name: configure pythonrc
  copy: src=home/pi/pythonrc
        dest=/home/pi/.pythonrc
        owner=pi
        group=pi
        mode=0644
        backup=yes
  tags:
  - pythonrc
  - configuration

- name: install python-osmgpsmap if Trusty
  apt:
    name: python-osmgpsmap
    state: present
  sudo: yes
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'trusty'
  tags:
  - trusty_only

# pip install --upgrade setuptools

# - name: pip install --upgrade setuptools
#   command: pip install --upgrade setuptools
#   tags:
#   - pip
#   - setuptools
#   sudo: yes
