# file: bossjones.common/tasks/setup_pocketsphinx.yml
---
# - name: Check if path exists
#   stat: path=/etc/monit/conf.d
#   register: check_path
#
# - name: It exists
#   debug: msg='Yay, the path exists!'
#   when: check_path.stat.exists
#
# - name: It doesn't exist
#   debug: msg="Boohoo, the path doesn't exist..."
#   when: check_path.stat.exists == false

- name: Check if sphinxbase exists
  stat: path=/home/pi/dev/bossjones-github/scarlett-dbus-poc/sphinxbase
  register: check_path_sphinxbase

- name: clone sphinxbase
  git: repo=https://github.com/cmusphinx/sphinxbase.git
       dest=/home/pi/dev/bossjones-github/scarlett-dbus-poc/sphinxbase
       clone=yes
  become: pi
  become_user: pi
  when: check_path_sphinxbase.stat.exists == false

- name: Check if pocketsphinx exists
  stat: path=/home/pi/dev/bossjones-github/scarlett-dbus-poc/pocketsphinx
  register: check_path_pocketsphinx

- name: clone pocketsphinx
  git: repo=https://github.com/cmusphinx/pocketsphinx.git
       dest=/home/pi/dev/bossjones-github/scarlett-dbus-poc/pocketsphinx
       clone=yes
  become: pi
  become_user: pi
  when: check_path_pocketsphinx.stat.exists == false

- name: clone sphinxbase into ~pi/dev/bossjones-github/scarlett-dbus-poc/sphinxbase
  git: repo=https://github.com/cmusphinx/sphinxbase.git
       dest=/home/pi/dev/bossjones-github/scarlett-dbus-poc/sphinxbase
       clone=no
       update=yes
       force=yes
  become: pi
  become_user: pi

- name: clone pocketsphinx into ~pi/dev/bossjones-github/scarlett-dbus-poc/pocketsphinx
  git: repo=https://github.com/cmusphinx/pocketsphinx.git
       dest=/home/pi/dev/bossjones-github/scarlett-dbus-poc/pocketsphinx
       clone=no
       update=yes
       force=yes
  become: pi
  become_user: pi

- name: clone py2cairo into ~pi/dev/bossjones-github/scarlett-dbus-poc/py2cairo
  git: repo=git://git.cairographics.org/git/py2cairo
       dest=/home/pi/dev/bossjones-github/scarlett-dbus-poc/py2cairo
       clone=no
       update=no
       accept_hostkey=true
  become: pi
  become_user: pi

- name: configure py2cairo pygobject glib gst-python
  copy: src=usr/local/bin/{{ item }}
        dest=/tmp/{{ item }}
        owner=pi
        group=pi
        mode=0755
  with_items:
  # - install_cairo.sh
  # - install_glib.sh
  # - install_pygobject.sh
  # - install_gst-python.sh
  - install_gst-plugins-espeak.sh
  - create_symlinks_virtualenv.sh
  - install_sphinxbase.sh
  - install_pocketsphinx.sh
  tags:
  - pocketsphinx
  - sphinxbase
  - shellscripts

# - name: compile py2cairo
#   shell: >
#     executable=/bin/bash
#     source `which virtualenvwrapper.sh` && mkvirtualenv --system-site-packages scarlett-dbus-poc
#   register: run_cmd
#   become: pi
#   become_user: pi

# - debug: var=run_cmd.stdout_lines

- name: compile py2cairo pygobject glib gst-python
  command: /tmp/{{ item }}
  with_items:
  # - install_cairo.sh
  # - install_pygobject.sh
  # - install_glib.sh
  # - install_gst-python.sh
  - install_gst-plugins-espeak.sh
  - create_symlinks_virtualenv.sh
  - install_sphinxbase.sh
  - install_pocketsphinx.sh
  tags:
  - pocketsphinx
  - sphinxbase
  - compile
  - cmusphinx
  become: pi
  become_user: pi
  ignore_errors: yes

- name: ldconfig after compiling
  command: "ldconfig"
  sudo: yes
