# file: bossjones.common/tasks/setup_python.yml
---

- name: Read the setup_python variables
  include_vars: "setup_python.yml"

- name: Make sure the setup_python packages are installed (Debian)
  apt:
    name: "{{item}}"
    state: present
  with_items: setup_python
  sudo: yes

- name: install pip
  easy_install: name=pip
                state=present

- name: install virtualenv
  pip: name=virtualenv
       state=present

- name: install virtualenvwrapper
  pip: name=virtualenvwrapper
       state=present

- name: install ipython
  pip: name=ipython
       state=present

# # Creates a virtualenv with the given name using mkvirtualenv. Run with
# #   ansible-playbook mkvirtualenv.yml -e 'hosts=ow1 virtualenv=syndicate_pro"
# - name: Run 'mkvirtualenv scarlett-dbus-poc'
#   shell: >
#     executable=/bin/bash
#     source `which virtualenvwrapper.sh` && mkvirtualenv scarlett-dbus-poc
#   register: run_cmd

# - debug: var=run_cmd.stdout_lines
