# file: bossjones.common/tasks/setup_gstreamer.yml
---

- name: Read the setup_python variables
  include_vars: "setup_gstreamer.yml"

- name: Add gstreamer-developers repo PPA
  apt_repository: repo='gstreamer-developers/ppa' state=present update_cache=yes
  sudo: yes

- name: Make sure the gstreamer_prereqs packages are installed (Debian)
  apt:
    name: "{{item}}"
    state: present
  with_items: gstreamer_prereqs
  sudo: yes

- name: install build-deps for gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-plugins-ugly gstreamer1.0-plugins-ugly
  apt: pkg={{ item }} state=build-dep
  with_items:
  - gstreamer1.0-plugins-base
  - gstreamer1.0-plugins-good
  - gstreamer1.0-plugins-ugly
