# file: bossjones.common/tasks/setup_scarlett.yml
---
- name: Creates virtualenv directory /home/pi/.virtualenvs
  pip: virtualenv=/home/pi/.virtualenvs/scarlett-dbus-poc
       virtualenv_command=/usr/local/bin/virtualenv-2.7
       virtualenv_site_packages=yes
  become: pi
  become_user: pi
