# file: bossjones.common/tasks/setup_pulseaudio.yml
---

- name: Read the setup_pulseaudio variables
  include_vars: "setup_pulseaudio.yml"

- name: Make sure the sound_libs packages are installed (Debian)
  apt:
    name: "{{item}}"
    state: present
  with_items: sound_libs
  sudo: yes
  tags:
  - audio
  - packages

- name: Make sure the setup_pulseaudio packages are installed (Debian)
  apt:
    name: "{{item}}"
    state: present
  with_items: setup_pulseaudio
  sudo: yes
  tags:
  - pulse
  - pulseaudio
  - packages

- name: configure pulseaudio
  copy: src=etc/pulse/{{ item }}
        dest=/etc/pulse/{{ item }}
        owner=root
        group=root
        mode=0644
        backup=yes
  with_items:
  - client.conf
  - daemon.conf
  - default.pa
  - system.pa
  tags:
  - pulse
  notify: clear pulseaudio cache
  when: configure_pulse is defined
  # NOTE if the above var is not defined, don't run this step at all

# NOTE: This fixes 14.04 ALC892 Low sound issue
# Source: http://askubuntu.com/questions/456425/alc892-low-sound-issue-fixed-with-changing-alsa-config-why-does-it-work
- name: configure /etc/modprobe.d/alsa-base.conf
  copy: src=etc/modprobe.d/alsa-base.conf
        dest=/etc/modprobe.d/alsa-base.conf
        owner=root
        group=root
        mode=0644
        backup=yes
  tags:
  - alsa
  - configuration
  - sound

- name: configure alsa-info.sh
  copy: src=usr/local/bin/{{ item }}
        dest=/tmp/{{ item }}
        owner=pi
        group=pi
        mode=0755
  with_items:
  - alsa-info.sh
  tags:
  - alsa
  - shellscripts
