# file: bossjones.common/tasks/setup_espeak.yml
---

- name: Read the setup_espeak variables
  include_vars: "setup_espeak.yml"

  tasks:
  - name: Make sure the setup_espeak packages are installed (Debian)
    apt:
      name: "{{item}}"
      state: present
    with_items: setup_espeak
    register: output
    changed_when: "'0 upgraded, 0 newly installed, 0 to remove' not in output.stdout and 'not upgraded' not in output.stdout"
    sudo: yes
    tags:
    - espeak

# ##############################################################################################################
# # HOW TO INSTALL gst-plugins-espeak : gstreamer 1.0
# # source: http://download.sugarlabs.org/sources/honey/gst-plugins-espeak/gst-plugins-espeak-0.4.0.tar.gz
# ##############################################################################################################
# export PYTHONPATH=/usr/local/lib/python2.7/site-packages
# export LD_LIBRARY_PATH=/usr/local/lib
# export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig
# export GST_PLUGIN_PATH=/usr/local/lib/gstreamer-1.0

# mkdir -p ~/packages
# cd ~/packages
# wget http://download.sugarlabs.org/sources/honey/gst-plugins-espeak/gst-plugins-espeak-0.4.0.tar.gz
# tar xvf gst-plugins-espeak-0.4.0.tar.gz
# cd gst-plugins-espeak-0.4.0
# ./configure
# make
# sudo make install

# ##############################################################################################################
# # For GStreamer 0.10.x, stay on v0.3.5x version
# # source: http://download.sugarlabs.org/sources/honey/gst-plugins-espeak/gst-plugins-espeak-0.3.5.tar.gz
# ##############################################################################################################

# export PYTHONPATH=/usr/local/lib/python2.7/site-packages
# export LD_LIBRARY_PATH=/usr/local/lib
# export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig
# export GST_PLUGIN_PATH=/usr/local/lib/gstreamer-0.10

# mkdir ~/packages
# cd ~/packages
# wget http://download.sugarlabs.org/sources/honey/gst-plugins-espeak/gst-plugins-espeak-0.3.5.tar.gz
# tar xvf gst-plugins-espeak-0.3.5.tar.gz
# cd gst-plugins-espeak-0.3.5
# ./configure
# make
# sudo make install
