# file: bossjones.common/tasks/setup_scarlett_user.yml
---
- name: Create Pi Group
  group: name=pi
         gid=1000
         state=present

- name: Create Pi User
  user: name=pi
        comment='Scarlett User Pi'
        shell=/bin/bash
        home=/home/pi
        group=pi
        uid=1000
        password=$6$UoXP1mRrk$S4k6yMNQkcX38ZP5OqEo7WaXm7ahly9qTEyYVDRP2kHBfh4ToShZHVcPYjKmYiGslDuiv7dmS/3.9sbZ5Z75u/
        state=present
        groups=adm,cdrom,sudo,dip,plugdev,lpadmin,sambashare,pulse,pulse-access,dailout,tty,audio

# Leaving this here because we need the folder structure in place to setup pocketsphinx
- name: Create Scarlett folders
  file: path=/home/pi/dev/bossjones-github/scarlett-dbus-poc
        state=directory
        mode=0755
        recurse=yes
        owner=pi
        group=pi

- name: clone scarlett-dbus-poc
  git: repo=https://github.com/bossjones/scarlett-dbus-poc.git
       dest=/home/pi/dev/bossjones-github/scarlett-dbus-poc
       update=no
       version=feature-fix-dobule
  become: pi
  become_user: pi


# use this to run scripts as a particular user
# source: http://stackoverflow.com/questions/21344777/how-to-switch-a-user-per-task-or-set-of-tasks
# become: yes
# become_user: some_user
