# file: bossjones.common/tasks/setup_python.yml
---

- name: Read the setup_python variables
  include_vars: "setup_python.yml"

  tasks:
  - name: Make sure the setup_python packages are installed (Debian)
    apt:
      name: "{{item}}"
      state: latest
    with_items: setup_python
    register: output
    changed_when: "'0 upgraded, 0 newly installed, 0 to remove' not in output.stdout and 'not upgraded' not in output.stdout"
    sudo: yes

  - name: install pip
    easy_install: name=pip state=latest

  - name: install virtualenv
    pip: name=virtualenv state=latest

  - name: install virtualenvwrapper
    pip: name=virtualenvwrapper state=latest

  - name: install ipython
    pip: name=ipython state=latest

  - name: Creates directory /home/pi/.virtualenvs
    pip: virtualenv=/home/pi/.virtualenvs/scarlett-dbus-poc virtualenv_command=virtualenv-2.7

  # # Creates a virtualenv with the given name using mkvirtualenv. Run with
  # #   ansible-playbook mkvirtualenv.yml -e 'hosts=ow1 virtualenv=syndicate_pro"
  # - name: Run 'mkvirtualenv scarlett-dbus-poc'
  #   shell: >
  #     executable=/bin/bash
  #     source `which virtualenvwrapper.sh` && mkvirtualenv scarlett-dbus-poc
  #   register: run_cmd

  # - debug: var=run_cmd.stdout_lines
