# file: bossjones.common/tasks/setup_pulseaudio.yml
---

- name: Read the setup_pulseaudio variables
  include_vars: "setup_pulseaudio.yml"

- name: Make sure the sound_libs packages are installed (Debian)
  apt:
    name: "{{item}}"
    state: present
  with_items: sound_libs
  sudo: yes
  tags:
  - audio
  - packages

- name: Make sure the setup_pulseaudio packages are installed (Debian)
  apt:
    name: "{{item}}"
    state: present
  with_items: setup_pulseaudio
  sudo: yes
  tags:
  - pulse
  - pulseaudio
  - packages

- name: configure pulseaudio
  copy: src=etc/pulse/{{ item }}
        dest=/etc/pulse/{{ item }}
        owner=root
        group=root
        mode=0644
        backup=yes
  with_items:
  - client.conf
  - daemon.conf
  - default.pa
  - system.pa
  tags:
  - pulse
  notify: clear pulseaudio cache
  when: configure_pulse is defined
  # NOTE if the above var is not defined, don't run this step at all
