# file: bossjones.common/tasks/setup_pocketsphinx.yml
---
- name: clone sphinxbase into ~pi/dev/bossjones-github/scarlett-dbus-poc/sphinxbase
  git: repo=https://github.com/cmusphinx/sphinxbase.git
       dest=/home/pi/dev/bossjones-github/scarlett-dbus-poc/sphinxbase
       clone=no
       update=no
  become: pi
  become_user: pi

- name: clone pocketsphinx into ~pi/dev/bossjones-github/scarlett-dbus-poc/pocketsphinx
  git: repo=https://github.com/cmusphinx/pocketsphinx.git
       dest=/home/pi/dev/bossjones-github/scarlett-dbus-poc/pocketsphinx
       clone=no
       update=no
  become: pi
  become_user: pi

- name: clone py2cairo into ~pi/dev/bossjones-github/scarlett-dbus-poc/py2cairo
  git: repo=git://git.cairographics.org/git/py2cairo
       dest=/home/pi/dev/bossjones-github/scarlett-dbus-poc/py2cairo
       clone=no
       update=no
       accept_hostkey=true
  become: pi
  become_user: pi

- name: configure py2cairo pygobject glib gst-python
  copy: src=usr/local/bin/{{ item }}
        dest=/tmp/{{ item }}
        owner=pi
        group=pi
        mode=0755
  with_items:
  # - install_cairo.sh
  # - install_glib.sh
  # - install_pygobject.sh
  # - install_gst-python.sh
  - create_symlinks_virtualenv.sh
  - install_sphinxbase.sh
  - install_pocketsphinx.sh
  tags:
  - pocketsphinx
  - sphinxbase
  - shellscripts

- name: compile py2cairo
  shell: >
    executable=/bin/bash
    source `which virtualenvwrapper.sh` && mkvirtualenv --system-site-packages scarlett-dbus-poc
  register: run_cmd
  become: pi
  become_user: pi

- debug: var=run_cmd.stdout_lines

- name: compile py2cairo pygobject glib gst-python
  command: /tmp/{{ item }}
  with_items:
  # - install_cairo.sh
  # - install_pygobject.sh
  # - install_glib.sh
  # - install_gst-python.sh
  - create_symlinks_virtualenv.sh
  - install_sphinxbase.sh
  - install_pocketsphinx.sh
  tags:
  - pocketsphinx
  - sphinxbase
  - compile
  - cmusphinx
  become: pi
  become_user: pi
  ignore_errors: yes

- name: ldconfig after compiling
  command: "ldconfig"
  sudo: yes
