# file: bossjones.common/tasks/setup_guestadditions.yml
---
- name: configure install_guest
  copy: src=usr/local/bin/install_guest.sh
        dest=/usr/local/bin/install_guest.sh
        owner=root
        group=root
        mode=0755
  tags:
  - guestadditions
  - configuration

- name: install guest additions
  command: "bash /usr/local/bin/install_guest.sh"
  tags:
  - guestadditions
