---
- hosts: all
  tasks:
    - name: ensure ntpd is at the present version
      apt: pkg={{ item }} state=present
      with_items:
      - ntp
      - ntpdate
      notify:
      - restart ntpd
  handlers:
    - name: restart ntpd
      service: name=ntpd state=restarted
