# file: bossjones.common/tasks/setup_pulseaudio.yml
---

- name: Read the setup_pulseaudio variables
  include_vars: "setup_pulseaudio.yml"

- name: Make sure the sound_libs packages are installed (Debian)
  apt:
    name: "{{item}}"
    state: present
  with_items: sound_libs
  sudo: yes
  tags:
  - audio
  - packages

- name: Make sure the setup_pulseaudio packages are installed (Debian)
  apt:
    name: "{{item}}"
    state: present
  with_items: setup_pulseaudio
  sudo: yes
  tags:
  - pulse
  - pulseaudio
  - packages

- name: configure pulseaudio
  copy: src=etc/pulse/{{ item }}
        dest=/etc/pulse/{{ item }}
        owner=root
        group=root
        mode=0644
        backup=yes
  with_items:
  - client.conf
  - daemon.conf
  - default.pa
  - system.pa
  tags:
  - pulse
  # notify: clear pulseaudio cache
  # when: configure_pulse is defined
  # NOTE if the above var is not defined, don't run this step at all

# NOTE: This fixes 14.04 ALC892 Low sound issue
# Source: http://askubuntu.com/questions/456425/alc892-low-sound-issue-fixed-with-changing-alsa-config-why-does-it-work
- name: configure /etc/modprobe.d/alsa-base.conf
  copy: src=etc/modprobe.d/alsa-base.conf
        dest=/etc/modprobe.d/alsa-base.conf
        owner=root
        group=root
        mode=0644
        backup=yes
  tags:
  - alsa
  - configuration
  - sound

# Disallow module loading after startup. This is a security feature since it disallows additional module loading during runtime and on user request.
# this file has the following change:
# sudo sed -i "s,DISALLOW_MODULE_LOADING=1,DISALLOW_MODULE_LOADING=0,g" /etc/default/pulseaudio
- name: configure /etc/init/pulseaudio.conf
  copy: src=etc/init/pulseaudio.conf
        dest=/etc/init/pulseaudio.conf
        owner=root
        group=root
        mode=0644
        backup=yes
  tags:
  - pulse
  - configuration
  - sound
  - pulseaudio

- name: configure alsa-info.sh
  copy: src=usr/local/bin/{{ item }}
        dest=/tmp/{{ item }}
        owner=pi
        group=pi
        mode=0755
  with_items:
  - alsa-info.sh
  tags:
  - alsa
  - shellscripts

# NEEDED FOR USB MIC MINI
# $ pacmd "load-module module-alsa-source source_name=input device=hw:1"
# $ pacmd "set-default-source input"
# $ pactl stat

- name: pacmd "load-module module-alsa-source source_name=input device=hw:1"
  command: pacmd "load-module module-alsa-source source_name=input device=hw:1"
  tags:
  - pulseaudio
  become: pi
  become_user: pi
  ignore_errors: yes

- name: pacmd "set-default-source input"
  command: pacmd "set-default-source input"
  tags:
  - pulseaudio
  become: pi
  become_user: pi
  ignore_errors: yes

# source: http://www.freedesktop.org/wiki/Software/PulseAudio/Documentation/User/PerfectSetup/
# GStreamer Applications

# Applications using the modern GStreamer media framework such as Rhythmbox or Totem can make use of the PulseAudio through gst-pulse, the PulseAudio plugin for GStreamer in gst-plugins-good. After installing it, you have to enable it as default audio sink and source for all GNOME applications by changing the GConf keys /system/gstreamer/0.10/default/audiosink and /system/gstreamer/0.10/default/audiosrc:

# gconftool -t string --set /system/gstreamer/0.10/default/audiosink pulsesink
# gconftool -t string --set /system/gstreamer/0.10/default/audiosrc pulsesrc
# Alternatively, you can make these changes with the GUI tool gstreamer-properties.

# The GStreamer plugin wraps playback, recording and the mixer interface.
