# file: bossjones.common/vars/Debian.yml
---
buildessential_packages:
  - autoconf
  - binutils-doc
  - bison
  - build-essential
  - flex
  - gettext
  - ncurses-dev
  - automake
  - bison
  - libtool
  - pkg-config
  - autopoint
  - autotools-dev
  - itstool
  - yasm
  - flex
  - bison
  - g++
  - autopoint
  - ragel
  - dh-autoreconf
  - anjuta
  - libssl-dev
  - libreadline-dev
  - wget
  - apt-transport-https
  - curl
  - openssl
  - perl
