---
- name: restart sshd
  service: name={{ sshd_service_name }} state=restarted

- name: restart pulseaudio
  service: name=pulseaudio state=restarted

- name: restart ntp
  service: name=ntp state=restarted

- name: clear pulseaudio cache
  command: "rm -r ~pi/.pulse;rm -r ~pi/.pulse-cookie;rm -r /tmp/pulse-*;rm -r ~pi/.config/pulse;killall -9 pulseaudio;"

