#!/usr/bin/env bash
# This hook is sourced after this virtualenv is activated.
# NOTE THIS HAS BEEN MODIFIED BY SCARLETT
# EXPECTING PATH: /home/pi/.virtualenvs/scarlett-dbus-poc/bin

export GSTREAMER=1.0
export PI_HOME=/home/pi
export MAIN_DIR=$PI_HOME/dev/bossjones-github/scarlett-dbus-poc
export VIRT_ROOT=$PI_HOME/.virtualenvs/scarlett-dbus-poc
export PKG_CONFIG_PATH=$VIRT_ROOT/lib/pkgconfig
export SCARLETT_CONFIG=$MAIN_DIR/tests/fixtures/.scarlett
export SCARLETT_HMM=$MAIN_DIR/tests/fixtures/model/hmm/en_US/hub4wsj_sc_8k
export SCARLETT_LM=$MAIN_DIR/tests/fixtures/lm/1602.lm
export SCARLETT_DICT=$MAIN_DIR/tests/fixtures/dict/1602.dic

echo "I have set the following env variables for this Scarlett virtualenv"
echo "*******************************************************************"
echo $GSTREAMER
echo $PI_HOME
echo $MAIN_DIR
echo $VIRT_ROOT
echo $PKG_CONFIG_PATH
echo $SCARLETT_CONFIG
echo $SCARLETT_HMM
echo $SCARLETT_LM
echo $SCARLETT_DICT
echo "*******************************************************************"
