#!/usr/bin/env bash

# source: https://github.com/sid137/ansible/blob/master/files/aliases.sh

alias sshn='ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no'
alias gip='pbpaste | gist -p'

# node.js
alias ni='npm install'

# shell
# http://majewsky.wordpress.com/2009/07/11/shutdown-your-machine-automatically-or-from-remote/
alias k9='kill -9'
alias gi='gem install'

alias lsdot="ls -A --group-directories-first | egrep '^\.'"
alias fs='find *'
alias spp='copy_public_ssh_key_to_host'
alias sdpi='sudo dpkg --install'

alias v='vim'
alias svim='sudo vim'
alias gu='chmod u+x'
alias tz='tar -zxvf'
alias tj='tar -xjvf'

#python
alias ipy="ipython"

#git
alias gl='git log --no-merges --graph --all --decorate --pretty="format:%C(red)%h%Creset - %C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue) %an%Creset"'
alias gla='gl --author'
alias gpo='git push origin'
alias gpom='git push origin master'
alias gnb='git-clean-branch'
alias gcl='git clone --recursive'
alias gb='git branch'
alias gco='git checkout'
alias gcb='git checkout -b'
alias gcm='git checkout master'
alias gcp='git cherry-pick'
alias gca='git commit -a -m'
alias gc='git commit'
alias gp='git push'
alias gpa='git push --tags'
alias gph='git push heroku master'
alias gps='git push staging staging:master'
alias gst='git status'
alias gsa='git stash save'
alias gss='git stash show -p'
alias ga='git add'
alias git-pup='git submodule foreach git pull origin master'

# Make
alias mk="make"
alias mkc="make clean"
alias mka="make all"
alias mkd='make d'
alias mkp='make python'
alias mkt='make test'
alias mkx='make && make clean'
alias mkf='make clean && make && make hex && make writeflash'

alias pd="cd ~/dev/${CURR_PROJ}"
alias ds='cd ~/Desktop'
alias m='more'
alias l='ls -lau -G'
alias sapt='aptitude search'
alias agi='sudo aptitude install -y'
alias ragi='sudo aptitude remove --purge'
alias vi='vim'
alias sagu='sudo apt-get update'
alias rii='ri -Tf ansi'

# Rake Tasks
alias rk='bundle exec rake'

# Scarlett tasks
# NOTE: These aliases are for easy debugging of things the usually go wrong w/ scarlett
alias scarlett_listen='cd ~/dev/bossjones-github/scarlett-dbus-poc/ && workon scarlett-dbus-poc && python scarlett_listener.py'
alias scarlett_task='cd ~/dev/bossjones-github/scarlett-dbus-poc/ && workon scarlett-dbus-poc && python scarlett_tasker.py'
alias scarlett_debug_listener='cd ~/dev/bossjones-github/scarlett-dbus-poc/ && workon scarlett-dbus-poc && GST_DEBUG=3,python:5,gnl*:5 python scarlett_listener.py 2>&1 | tee listener.log'
alias scarlett_dbus_cd='cd ~/dev/bossjones-github/scarlett-dbus-poc/'

alias scarlett_check_alsa='alsamixer'
alias scarlett_reinstall_pulse='sudo apt-get remove --purge alsa-base pulseaudio -y ;sudo apt-get install alsa-base pulseaudio -y;sudo alsa force-reload;sudo shutdown -r now'
alias scarlett_force_reload_alsa='sudo alsa force-reload;sudo shutdown -r now'
alias scarlett_clear_pulse_cache='rm -r ~pi/.pulse;rm -r ~pi/.pulse-cookie;rm -r /tmp/pulse-*;rm -r ~pi/.config/pulse;killall -9 pulseaudio;'
alias scarlett_list_usb_devices='lsusb'
alias scarlett_list_microphones='arecord -l'
alias scarlett_microphone_record_test='arecord -D plughw:1,0 /tmp/scarlett_microphone_test.wav'
alias scarlett_microphone_play_test='aplay /tmp/scarlett_microphone_test.wav'
alias scarlett_get_recording_settings="amixer -c 0 sget 'Mic',0"
alias scarlett_get_playback_settings="amixer -c 1"
alias scarlett_increase_capture_levels='alsamixer -c 0'
alias scarlett_microphone_record_test2='arecord -D plughw:0,0 -f cd /tmp/test.wav'
alias scarlett_microphone_play_sound_test2='aplay /tmp/test.wav'
alias scarlett_check_pocketsphinx_gst_plugin_exists='gst-inspect-1.0 | grep sphinx'

scarlett_setup_env_vars(){
  export GSTREAMER=1.0
  export PI_HOME=/home/pi
  export MAIN_DIR=$PI_HOME/dev/bossjones-github/scarlett-dbus-poc
  export VIRT_ROOT=$PI_HOME/.virtualenvs/scarlett-dbus-poc
  export PKG_CONFIG_PATH=$VIRT_ROOT/lib/pkgconfig
  export SCARLETT_CONFIG=$MAIN_DIR/tests/fixtures/.scarlett
  export SCARLETT_HMM=$MAIN_DIR/tests/fixtures/model/hmm/en_US/hub4wsj_sc_8k
  export SCARLETT_LM=$MAIN_DIR/tests/fixtures/lm/1602.lm
  export SCARLETT_DICT=$MAIN_DIR/tests/fixtures/dict/1602.dic
}
