# file: scarlett.common/vars/main.yml
---
vars:
  GSTREAMER: '1.0'
  PI_HOME: '/home/pi'
  LANGUAGE_ID: 1473
  GITHUB_REPO_NAME: "scarlett-dbus-poc"
  GITHUB_REPO_ORG: "bossjones"
  MAIN_DIR: "{{ PI_HOME }}/dev/bossjones-github/{{ GITHUB_REPO_NAME }}"
  VIRT_ROOT: "{{ PI_HOME }}/.virtualenvs/{{ GITHUB_REPO_NAME }}"
  PKG_CONFIG_PATH: "{{ VIRT_ROOT }}/lib/pkgconfig"
  SCARLETT_CONFIG: "{{ MAIN_DIR }}/tests/fixtures/.scarlett"
  SCARLETT_HMM: "{{ MAIN_DIR }}/.virtualenvs/{{ GITHUB_REPO_NAME }}/share/pocketsphinx/model/en-us/en-us"
  SCARLETT_LM: "{{ MAIN_DIR }}/tests/fixtures/lm/{{ LANGUAGE_ID }}.lm"
  SCARLETT_DICT: "{{ MAIN_DIR }}/tests/fixtures/dict/{{ LANGUAGE_ID }}.dic"
  LD_LIBRARY_PATH: "{{ VIRT_ROOT }}/lib"
  GST_PLUGIN_PATH: "{{ VIRT_ROOT }}/lib/gstreamer-{{ GSTREAMER }}"
