# file: scarlett.common/vars/main.yml
---

#  53 export WORKON_HOME=$HOME/.virtualenvs
#  54 export PROJECT_HOME=$HOME/dev
#  55 export VIRTUALENVWRAPPER_PYTHON=/usr/local/bin/python
#  56 export VIRTUALENVWRAPPER_VIRTUALENV=/usr/local/bin/virtualenv
#  57 export VIRTUALENVWRAPPER_SCRIPT=/usr/local/bin/virtualenvwrapper.sh
#  58 source /usr/local/bin/virtualenvwrapper.sh
#  59 export PYTHONSTARTUP=~/.pythonrc
#  60 export PIP_DOWNLOAD_CACHE=$HOME/.pip/cache

base_vars:
  PYTHON_VERSION_MAJOR: '3'
  PYTHON_VERSION: '3.5'
  GSTREAMER: '1.0'
  USER: 'pi'
  USER_HOME: '/home/pi'
  LANGUAGE_ID: 1473
  GITHUB_BRANCH: "master"
  GITHUB_REPO_NAME: "scarlett_os"
  GITHUB_REPO_ORG: "bossjones"

virtualenv_vars:
  MAIN_DIR: "{{ base_vars.USER_HOME }}/dev/bossjones-github/{{ base_vars.GITHUB_REPO_NAME }}"
  VIRT_ROOT: "{{ base_vars.USER_HOME }}/.virtualenvs/{{ base_vars.GITHUB_REPO_NAME }}"
  WORKON_HOME: "{{ base_vars.USER_HOME }}/.virtualenvs"
  PROJECT_HOME: "{{ base_vars.USER_HOME }}/dev"
  VIRTUALENVWRAPPER_PYTHON: "/usr/bin/python3"
  VIRTUALENVWRAPPER_VIRTUALENV: "/usr/local/bin/virtualenv"
  VIRTUALENVWRAPPER_SCRIPT: "/usr/local/bin/virtualenvwrapper.sh"
  PYTHONSTARTUP: "$HOME/.pythonrc"
  PIP_DOWNLOAD_CACHE: "$HOME/.pip/cache"

build_vars:
  PKG_CONFIG_PATH: "{{ virtualenv_vars.VIRT_ROOT }}/lib/pkgconfig"
  LD_LIBRARY_PATH: "{{ virtualenv_vars.VIRT_ROOT }}/lib"
  GST_PLUGIN_PATH: "{{ virtualenv_vars.VIRT_ROOT }}/lib/gstreamer-{{ base_vars.GSTREAMER }}"

scarlett_vars:
  SCARLETT_CONFIG: "{{ virtualenv_vars.MAIN_DIR }}/tests/fixtures/.scarlett"
  SCARLETT_HMM: "{{ base_vars.USER_HOME }}/.virtualenvs/{{ base_vars.GITHUB_REPO_NAME }}/share/pocketsphinx/model/en-us/en-us"
  SCARLETT_LM: "{{ virtualenv_vars.MAIN_DIR }}/tests/fixtures/lm/{{ base_vars.LANGUAGE_ID }}.lm"
  SCARLETT_DICT: "{{ virtualenv_vars.MAIN_DIR }}/tests/fixtures/dict/{{ base_vars.LANGUAGE_ID }}.dic"
