# file: bossjones.common/tasks/build_essentials.yml
---

- name: Read the family variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: Make sure the packages are installed (Debian)
  apt:
    name: "{{item}}"
    state: present
  with_items: "{{ buildessential_packages }}"
  when: ansible_os_family == "Debian"
  become: true
  tags:
  - build_essentials
  - packages
  - install_packages
