# file: bossjones.common/tasks/finalize.yml
---
- name: reboot the servers
  command: shutdown -r now
  sudo: true

- name: Wait for it to come back
  local_action: wait_for host=${inventory_hostname} port=2222 delay=5 timeout=300
  sudo: false

- name: install kernel headers
  apt: pkg=linux-headers-${ansible_kernel}
