# file: bossjones.common/tasks/main.yml
---

- name: Update apt
  apt: update_cache=yes
  sudo: yes

- name: setup motd
  copy: src=etc/motd
        dest=/etc/motd
        owner=root
        group=root
        mode=0644
  tags:
  - motd

- name: provision scarlett node
  include: build_essentials.yml

- name: bootstrap
  include: bootstrap.yml

# - name: guest additions
#   include: setup_guestadditions.yml

- name: setup_sshd
  include: setup_sshd.yml

- name: setup_ntp
  include: setup_ntp.yml

- name: setup_pulseaudio
  include: setup_pulseaudio.yml

- name: setup_espeak
  include: setup_espeak.yml

- name: setup_gstreamer
  include: setup_gstreamer.yml

- name: gnome_gtk_prereqs
  include: gnome_gtk_prereqs.yml

- name: setup_python
  include: setup_python.yml

- name: setup_scarlett_user
  include: setup_scarlett_user.yml

- name: setup_scarlett
  include: setup_scarlett.yml

- name: setup_pocketsphinx
  include: setup_pocketsphinx.yml

- name: setup_rbenv
  include: setup_rbenv.yml

- name: setup_bash_it
  include: setup_bash_it.yml

- name: debug_packages
  include: debug_packages.yml

- name: setup_dbus_examples
  include: setup_dbus_examples.yml

  # include: bootstrap.yml
  # include: setup_guestadditions.yml
  # include: setup_sshd.yml
  # include: setup_ntp.yml
  # include: setup_pulseaudio.yml
  # include: setup_espeak.yml
  # include: setup_gstreamer.yml
  # include: gnome_gtk_prereqs.yml
  # include: setup_python.yml
  # include: setup_scarlett_user.yml
  # include: setup_scarlett.yml
  # include: setup_pocketsphinx.yml
