# file: bossjones.common/tasks/setup_scarlett_user.yml
---
- name: Create Pi Group
  group: name=pi
         gid=1000
         state=present

- name: Create vboxusers Group
  group: name=vboxusers
         state=present
         system=yes

- name: Create Pi User
  user: name=pi
        comment='Scarlett User Pi'
        shell=/bin/bash
        home=/home/pi
        group=pi
        uid=1000
        password=$6$UoXP1mRrk$S4k6yMNQkcX38ZP5OqEo7WaXm7ahly9qTEyYVDRP2kHBfh4ToShZHVcPYjKmYiGslDuiv7dmS/3.9sbZ5Z75u/
        state=present
        groups=adm,cdrom,sudo,dip,plugdev,lpadmin,sambashare,pulse,pulse-access,tty,audio,vboxusers

# NOTE: missing group dailout

- name: Create ~pi/dev and ~pi/dev/bossjones-github/scarlett_os folders
  file: path=/home/pi/dev/bossjones-github/scarlett_os
        state=directory
        mode=0755
        recurse=yes
        owner=pi
        group=pi

- name: clone scarlett_os into /home/pi/dev/bossjones-github/scarlett_os
  git: repo=https://github.com/bossjones/scarlett_os.git
       dest=/home/pi/dev/bossjones-github/scarlett_os
       update=no
       version="{{base_vars.GITHUB_BRANCH}}"
       refspec=+refs/pull/*:refs/heads/*
  become: pi
  become_user: pi


# Leaving this here because we need the folder structure in place to setup pocketsphinx
- name: Create ~pi/dev and ~pi/dev/bossjones-github/scarlett-dbus-poc folders
  file: path=/home/pi/dev/bossjones-github/scarlett-dbus-poc
        state=directory
        mode=0755
        recurse=yes
        owner=pi
        group=pi

- name: clone scarlett-dbus-poc into /home/pi/dev/bossjones-github/scarlett-dbus-poc
  git: repo=https://github.com/bossjones/scarlett-dbus-poc.git
       dest=/home/pi/dev/bossjones-github/scarlett-dbus-poc
       update=no
       version="{{base_vars.GITHUB_BRANCH}}"
       refspec=+refs/pull/*:refs/heads/*
  become: pi
  become_user: pi

- name: clone scarlett into /home/pi/dev/bossjones-github/scarlett
  git: repo=https://github.com/bossjones/scarlett.git
       dest=/home/pi/dev/bossjones-github/scarlett
       update=no
       version=master
       refspec=+refs/pull/*:refs/heads/*
  become: pi
  become_user: pi

- name: clone scarlett into /home/pi/dev/bossjones-github/scarlett_os
  git: repo=https://github.com/bossjones/scarlett_os.git
       dest=/home/pi/dev/bossjones-github/scarlett_os
       update=no
       version=master
       refspec=+refs/pull/*:refs/heads/*
  become: pi
  become_user: pi

- name: Install scarlett requirements.txt into the virtualenv scarlett_os
  pip: requirements=/home/pi/dev/bossjones-github/scarlett_os/{{ item }}
       virtualenv=/home/pi/.virtualenvs/scarlett_os
       executable=/usr/local/bin/pip3
  with_items:
  - requirements.txt
  - requirements_dev.txt
  become: pi
  become_user: pi
  tags:
  - python
  - pip
  - requirements

# TODO: Make sure we downgrade path.py to v7.7.1, this is untested
# SOURCE: http://stackoverflow.com/questions/32252122/installing-ipython-importerror-cannot-import-name-path
- name: downgrade path.py to v7.7.1 in virtualenv scarlett_os
  pip: name=path.py version=7.7.1
       virtualenv=/home/pi/.virtualenvs/scarlett_os
       extra_args='-I'
       executable=/usr/local/bin/pip3
  become: pi
  become_user: pi
  tags:
  - python
  - pip
  - requirements

# TODO: Get this installed into requirements.txt instead of here !!!!!!!!!!!!
- name: Install colorlog into the virtualenv
  pip: name=colorlog
       virtualenv=/home/pi/.virtualenvs/scarlett_os
       executable=/usr/local/bin/pip3
  become: pi
  become_user: pi
  tags:
  - python
  - pip
  - requirements

- name: clone scarlett-gstreamer-pocketsphinx-demo into /home/pi/dev/bossjones-github/scarlett-gstreamer-pocketsphinx-demo
  git: repo=https://github.com/bossjones/scarlett-gstreamer-pocketsphinx-demo.git
       dest=/home/pi/dev/bossjones-github/scarlett-gstreamer-pocketsphinx-demo
       update=no
       version=master
       refspec=+refs/pull/*:refs/heads/*
  become: pi
  become_user: pi

- name: Install scarlett requirements.txt into the virtualenv scarlett-dbus-poc pip3
  pip: requirements=/home/pi/dev/bossjones-github/scarlett/{{ item }}
       virtualenv=/home/pi/.virtualenvs/scarlett-dbus-poc
       executable=/usr/local/bin/pip3
  with_items:
  - requirements.txt
  - requirements_plugins.txt
  - requirements_dev.txt
  become: pi
  become_user: pi
  tags:
  - python
  - pip
  - requirements

# TODO: Make sure we downgrade path.py to v7.7.1, this is untested
# SOURCE: http://stackoverflow.com/questions/32252122/installing-ipython-importerror-cannot-import-name-path
- name: Install scarlett requirements.txt into the virtualenv scarlett-dbus-poc
  pip: name=path.py version=7.7.1
       virtualenv=/home/pi/.virtualenvs/scarlett-dbus-poc
       extra_args='-I'
       executable=/usr/local/bin/pip3
  become: pi
  become_user: pi
  tags:
  - python
  - pip
  - requirements

# TODO: Get this installed into requirements.txt instead of here !!!!!!!!!!!!
- name: Install colorlog into the virtualenv
  pip: name=colorlog
       virtualenv=/home/pi/.virtualenvs/scarlett-dbus-poc
       executable=/usr/local/bin/pip3
  become: pi
  become_user: pi
  tags:
  - python
  - pip
  - requirements
