# file: bossjones.common/tasks/setup_sshd.yml
---

- name: Read the setup_sshd variables
  include_vars: "setup_sshd.yml"

- name: configure sudoers
  template: src="{{ role_path }}/templates/etc/sudoers.j2"
            dest=/etc/sudoers
            validate='visudo -cf %s'
            owner=root
            group=root
            mode=00600
            backup=yes
  tags:
  - sudoers
  - configuration

- name: configure ssh
  template: src="{{ role_path }}/templates/etc/ssh/{{ item }}.j2"
            dest=/etc/ssh/{{ item }}
            validate='/usr/sbin/sshd -t -f %s'
            owner=root
            group=root
            mode=00644
            backup=yes
  with_items:
  - sshd_config
  tags:
  - ssh
  - configuration
  notify: restart sshd

- name: enable sshd
  service: name={{ sshd_service_name }}
           state=running
           enabled=yes
  tags: service

- name: restart sshd
  service: name={{ sshd_service_name }}
           state=restarted
