# file: bossjones.common/tasks/setup_pocketsphinx.yml
---
- name: Check if sphinxbase exists and clone
  shell: |
    if [ -d "{{virtualenv_vars.MAIN_DIR}}/sphinxbase" ]; then
        cd "{{virtualenv_vars.MAIN_DIR}}/sphinxbase"
        git status && git add . && git reset --hard && git fetch --all
        git checkout 74370799d5b53afc5b5b94a22f5eff9cb9907b97
        git clean -ffdx
        git submodule update --init --recursive
    else
        cd "{{virtualenv_vars.MAIN_DIR}}"
        rm -rfv "{{virtualenv_vars.MAIN_DIR}}/sphinxbase"
        git clone https://github.com/cmusphinx/sphinxbase.git .
        cd sphinxbase
        git checkout 74370799d5b53afc5b5b94a22f5eff9cb9907b97
    fi
  register: sphinxbase_cmd_result
  become: pi
  become_user: pi
  args:
    executable: /bin/bash

- name: Check if pocketsphinx exists and clone
  shell: |
    if [ -d "{{virtualenv_vars.MAIN_DIR}}/pocketsphinx" ]; then
        cd "{{virtualenv_vars.MAIN_DIR}}/pocketsphinx"
        git status && git add . && git reset --hard && git fetch --all
        git checkout 68ef5dc6d48d791a747026cd43cc6940a9e19f69
        git clean -ffdx
        git submodule update --init --recursive
    else

        cd "{{virtualenv_vars.MAIN_DIR}}"
        rm -rfv "{{virtualenv_vars.MAIN_DIR}}/pocketsphinx"
        git clone https://github.com/cmusphinx/pocketsphinx.git .
        cd pocketsphinx
        git checkout 68ef5dc6d48d791a747026cd43cc6940a9e19f69
    fi
  register: pocketsphinx_cmd_result
  become: pi
  become_user: pi
  args:
    executable: /bin/bash

- name: python3-gi symlink gi
  shell: |
    cd {{virtualenv_vars.VIRT_ROOT}}/lib/python3.5/site-packages/
    ln -sf /usr/lib/python3/dist-packages/gi
  register: symlink_python3_gi
  become: pi
  become_user: pi
  args:
    executable: /bin/bash

- name: configure py2cairo pygobject glib gst-python
  template: src="{{ role_path }}/templates/usr/local/bin/{{ item }}.j2"
            dest=/usr/local/bin/{{ item }}
            owner=pi
            group=pi
            mode=0755
  with_items:
  - install_gst-plugins-espeak.sh
  # - create_symlinks_virtualenv.sh
  - install_sphinxbase.sh
  - install_pocketsphinx.sh
  tags:
  - pocketsphinx
  - sphinxbase
  - shellscripts

- name: compile py2cairo pygobject glib gst-python
  command: /usr/local/bin/{{ item }}
  with_items:
  - install_gst-plugins-espeak.sh
  # - create_symlinks_virtualenv.sh
  - install_sphinxbase.sh
  - install_pocketsphinx.sh
  tags:
  - pocketsphinx
  - sphinxbase
  - compile
  - cmusphinx
  become: "{{base_vars.USER}}"
  become_user: "{{base_vars.USER}}"
  ignore_errors: yes

- name: ldconfig after compiling
  command: "ldconfig"
  become: true
