# file: bossjones.common/tasks/gnome_gtk_prereqs.yml
---
- name: clone bash_it
  git: repo=https://github.com/Bash-it/bash-it.git
       dest="/home/{{base_vars.USER}}/.bash_it"
       update=no
       depth=1
  become: "{{base_vars.USER}}"
  become_user: "{{base_vars.USER}}"

# Leaving this here because we need the folder structure in place to setup pocketsphinx
- name: Create ~pi/.bash_it/themes/devops
  file: path="/home/{{base_vars.USER}}/.bash_it/themes/devops"
        state=directory
        mode=0755
        recurse=yes
        owner="{{base_vars.USER}}"
        group="{{base_vars.USER}}"

- name: configure devops.theme.bash
  copy: src="home/{{base_vars.USER}}/bash_it/themes/devops/devops.theme.bash"
        dest="/home/{{base_vars.USER}}/.bash_it/themes/devops/devops.theme.bash"
        owner="{{base_vars.USER}}"
        group="{{base_vars.USER}}"
        mode=0644
        backup=yes
  tags:
  - bash_it
  - configuration

- name: configure bash_profile
  copy: src="home/{{base_vars.USER}}/bash_profile"
        dest="/home/{{base_vars.USER}}/.bash_profile"
        owner="{{base_vars.USER}}"
        group="{{base_vars.USER}}"
        mode=0644
        backup=yes
  tags:
  - bash_profile
  - configuration

- name: configure bashrc
  copy: src="home/{{base_vars.USER}}/bashrc"
        dest="/home/{{base_vars.USER}}/.bashrc"
        owner="{{base_vars.USER}}"
        group="{{base_vars.USER}}"
        mode=0644
        backup=yes
  tags:
  - bashrc
  - configuration

- name: configure .scarlett_aliases
  copy: src="home/{{base_vars.USER}}/scarlett_aliases"
        dest="/home/{{base_vars.USER}}/.scarlett_aliases"
        owner="{{base_vars.USER}}"
        group="{{base_vars.USER}}"
        mode=0644
        backup=yes
  tags:
  - scarlett_aliases
  - configuration
