# file: bossjones.common/tasks/setup_dbus_examples.yml
---
- name: Create ~pi/dev/gnome
  file: path=/home/pi/dev/gnome
        state=directory
        mode=0755
        recurse=yes
        owner=pi
        group=pi

- name: Check if hello-dbus exists
  stat: path=/home/pi/dev/gnome/hello-dbus
  register: check_path_hello_dbus

- name: Check if btk exists
  stat: path=/home/pi/dev/gnome/btk
  register: check_path_btk

- name: Check if pydbus exists
  stat: path=/home/pi/dev/gnome/pydbus
  register: check_path_pydbus

- name: Check if rhythmbox exists
  stat: path=/home/pi/dev/gnome/rhythmbox
  register: check_path_rhythmbox

- name: Check if hexchat exists
  stat: path=/home/pi/dev/gnome/hexchat
  register: check_path_hexchat

- name: Check if orca exists
  stat: path=/home/pi/dev/gnome/orca
  register: check_path_orca

- name: Check if gimp exists
  stat: path=/home/pi/dev/gnome/gimp
  register: check_path_gimp

- name: Check if dasher exists
  stat: path=/home/pi/dev/gnome/dasher
  register: check_path_dasher

- name: Check if accerciser exists
  stat: path=/home/pi/dev/gnome/accerciser
  register: check_path_accerciser

- name: Check if glib exists
  stat: path=/home/pi/dev/gnome/glib
  register: check_path_glib

- name: Check if gnome-builder exists
  stat: path=/home/pi/dev/gnome/gnome-builder
  register: check_path_gnome_builder

- name: Check if pygobject exists
  stat: path=/home/pi/dev/gnome/pygobject
  register: check_path_pygobject

- name: Check if gobject-introspection exists
  stat: path=/home/pi/dev/gnome/gobject-introspection
  register: check_path_gobject_introspection

- name: Check if gtk exists
  stat: path=/home/pi/dev/gnome/gtk
  register: check_path_gtk

- name: Check if pygtk exists
  stat: path=/home/pi/dev/gnome/pygtk
  register: check_path_pygtk

- name: clone https://github.com/lvht/hello-dbus
  git: repo=https://github.com/lvht/hello-dbus
       dest=/home/pi/dev/gnome/hello-dbus
       clone=yes
  become: pi
  become_user: pi
  when: check_path_hello_dbus.stat.exists == false

- name: clone https://github.com/lvht/btk.git
  git: repo=https://github.com/lvht/btk.git
       dest=/home/pi/dev/gnome/btk
       clone=yes
  become: pi
  become_user: pi
  when: check_path_btk.stat.exists == false

- name: clone https://github.com/LEW21/pydbus.git
  git: repo=https://github.com/LEW21/pydbus.git
       dest=/home/pi/dev/gnome/pydbus
       clone=yes
  become: pi
  become_user: pi
  when: check_path_pydbus.stat.exists == false

- name: clone https://github.com/GNOME/rhythmbox.git
  git: repo=https://github.com/GNOME/rhythmbox.git
       dest=/home/pi/dev/gnome/rhythmbox
       clone=yes
  become: pi
  become_user: pi
  when: check_path_rhythmbox.stat.exists == false

- name: clone https://github.com/hexchat/hexchat.git
  git: repo=https://github.com/hexchat/hexchat.git
       dest=/home/pi/dev/gnome/hexchat
       clone=yes
  become: pi
  become_user: pi
  when: check_path_hexchat.stat.exists == false

- name: clone https://github.com/GNOME/orca.git
  git: repo=https://github.com/GNOME/orca.git
       dest=/home/pi/dev/gnome/orca
       clone=yes
  become: pi
  become_user: pi
  when: check_path_orca.stat.exists == false

- name: clone https://github.com/GNOME/gimp.git
  git: repo=https://github.com/GNOME/gimp.git
       dest=/home/pi/dev/gnome/gimp
       clone=yes
  become: pi
  become_user: pi
  when: check_path_gimp.stat.exists == false

- name: clone https://github.com/GNOME/dasher.git
  git: repo=https://github.com/GNOME/dasher.git
       dest=/home/pi/dev/gnome/dasher
       clone=yes
  become: pi
  become_user: pi
  when: check_path_dasher.stat.exists == false

- name: clone https://github.com/GNOME/accerciser.git
  git: repo=https://github.com/GNOME/accerciser.git
       dest=/home/pi/dev/gnome/accerciser
       clone=yes
  become: pi
  become_user: pi
  when: check_path_accerciser.stat.exists == false

- name: clone https://github.com/GNOME/glib.git
  git: repo=https://github.com/GNOME/glib.git
       dest=/home/pi/dev/gnome/glib
       clone=yes
  become: pi
  become_user: pi
  when: check_path_glib.stat.exists == false

- name: clone https://git.gnome.org/browse/pygobject
  git: repo=https://git.gnome.org/browse/pygobject
       dest=/home/pi/dev/gnome/pygobject
       clone=yes
       accept_hostkey=true
  become: pi
  become_user: pi
  when: check_path_pygobject.stat.exists == false

- name: clone https://git.gnome.org/browse/gnome-builder
  git: repo=https://git.gnome.org/browse/gnome-builder
       dest=/home/pi/dev/gnome/gnome-builder
       clone=yes
       accept_hostkey=true
  become: pi
  become_user: pi
  when: check_path_gnome_builder.stat.exists == false

- name: clone https://git.gnome.org/browse/gobject-introspection
  git: repo=https://git.gnome.org/browse/gobject-introspection
       dest=/home/pi/dev/gnome/gobject-introspection
       clone=yes
       accept_hostkey=true
  become: pi
  become_user: pi
  when: check_path_gobject_introspection.stat.exists == false

- name: clone https://git.gnome.org/browse/gtk+
  git: repo=https://git.gnome.org/browse/gtk+
       dest=/home/pi/dev/gnome/gtk+
       clone=yes
       accept_hostkey=true
  become: pi
  become_user: pi
  when: check_path_gtk.stat.exists == false

- name: clone https://git.gnome.org/browse/pygtk
  git: repo=https://git.gnome.org/browse/pygtk
       dest=/home/pi/dev/gnome/pygtk
       clone=yes
       accept_hostkey=true
  become: pi
  become_user: pi
  when: check_path_pygtk.stat.exists == false
