---
- name: Add ppa:brightbox/ruby-ng repo PPA
  apt_repository: repo='ppa:brightbox/ruby-ng' state=present update_cache=yes
  become: true
  tags:
  - ruby
  - packages

- name: Make sure the ruby2.2 packages are installed (Debian)
  apt:
    name: "{{item}}"
    state: present
  with_items:
  - ruby2.2
  - ruby2.2-dev
  become: true
  tags:
  - ruby
  - packages
  - install_packages

- name: "Install bundler"
  gem: name=bundler state=present

- name: configure .gemrc
  copy: src="home/{{base_vars.USER}}/gemrc"
        dest="/home/{{base_vars.USER}}/.gemrc"
        owner="{{base_vars.USER}}"
        group="{{base_vars.USER}}"
        mode=0644
        backup=yes
  tags:
  - ruby
  - gem
  - configuration
