---
 - name: Add Oracle Java PPA
   apt_repository: repo="ppa:webupd8team/java" validate_certs=False

 - name: Automatically select the Oracle License
   shell: echo debconf shared/accepted-oracle-license-v1-1 select true | debconf-set-selections
   changed_when: false

 - name: Install Oracle Java
   apt: pkg=oracle-java7-installer update-cache=yes state=latest
