---
- name: Add ppa:brightbox/ruby-ng repo PPA
  apt_repository: repo='ppa:brightbox/ruby-ng' state=present update_cache=yes
  sudo: yes
  tags:
  - ruby
  - packages

- name: Make sure the ruby2.2 packages are installed (Debian)
  apt:
    name: "{{item}}"
    state: present
  with_items:
  - ruby2.2
  - ruby2.2-dev
  sudo: yes
  tags:
  - ruby
  - packages
  - install_packages

- name: "Install bundler"
  gem: name=bundler state=present

- name: configure .gemrc
  copy: src=home/pi/gemrc
        dest=/home/pi/.gemrc
        owner=pi
        group=pi
        mode=0644
        backup=yes
  tags:
  - ruby
  - gem
  - configuration
